name: khetibaadi
description: SyntaxError

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_tts: ^2.1.0
  image_picker: ^0.6.6+4
  firebase_ml_vision: ^0.10.0
  firebase_mlkit_language: ^1.1.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

